 apiVersion: networking.k8s.io/v1
 kind: Ingress
 metadata:
   name: iamlab-isvawrp-rp1
   annotations:
     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
     nginx.ingress.kubernetes.io/affinity: "cookie"
 spec:
  tls:
  - hosts:
    - www.iamlab.ibm.com
  rules:
  - host: www.iamlab.ibm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iamlab-isvawrp-rp1
            port:
              number: 9443
