
#
# This file contains the default values used by the helm chart installation.
#

###############################################################################
# Global configuration which is available to all sub-charts

global:
  # Common image variables
  image:
    configrepository:   ibmcom/verify-access:10.0.3.0
    wrprepository:   ibmcom/verify-access-wrp:10.0.3.0
    runtimerepository:   ibmcom/verify-access-runtime:10.0.3.0
    dscrepository:   ibmcom/verify-access-dsc:10.0.3.0
    dbrepository: ibmcom/verify-access-postgresql:10.0.3.0
    ldaprepository: ibmcom/verify-access-openldap:10.0.3.0
    pullPolicy:   IfNotPresent

  # Image credentials.
  imageCredentials:
    dockerSecret: "dockerlogin"

  # Container configuration.
  container:
    snapshot:           ""
    fixpacks:           ""
    adminSecret:        "helm-isvaadmin"
    timezone:           "Etc/UTC"

  # Persistence Storage
  persistence:
    enabled:                true
    useDynamicProvisioning: true

  # Config container service Name
  configservicename: isvaconfig

###############################################################################
# Configuration container variables.

isvaconfig:

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 2Gi
      cpu:    2000m

  # Service Configuration.
  service:
    type: NodePort
    nodePort:
  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        5Gi

###############################################################################
# Web Reverse Proxy container variables.

isvawrp:

  # Container configuration.
  container:
    instances:
      - name: rp1
        servicename: isvawrprp1
        servicetype: ClusterIP
        nodePort:
        replicas: 1

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

###############################################################################
# Runtime container variables.

isvaruntime:

  # Container configuration.
  container:
    enabled:  true
    replicas: 1

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 500Mi
      cpu:    500m
    limits:
      memory: 2Gi
      cpu:    2000m

  service:
    servicename: isvaruntime

###############################################################################
# DSC container variables.

isvadsc:

  # Container configuration.
  container:
    enabled:    true
    useReplica: false

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  service:
    servicename: isvadsc

###############################################################################
# postgresql container variables.

isvapostgresql:

  # Container configuration.
  container:
    enabled: true
    keySecretName: "postgresql-keys"

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  service:
    servicename: postgresql

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        5Gi

###############################################################################
# openldap container variables.

isvaopenldap:

  # Container configuration.
  container:
    enabled: true
    keySecretName: "openldap-keys"

  # Resource Configuration.
  # Information on computing resources can be found at:
  #    http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    requests:
      memory: 512Mi
      cpu:    500m
    limits:
      memory: 1Gi
      cpu:    1000m

  service:
    servicename: openldap

  # Data Volume
  dataVolume:

    # Specify the name of the Existing Claim to be used by your application.
    # An empty string means that an existing claim will not be used.
    existingClaimName: ""

    # Specify the name of the storage class.  Any empty string means that we
    # won't use a storage class.
    storageClassName: ""

    size:        5Gi
