version: '3'

volumes:
  isvaconfig:
  libldap:
  ldapslapd:
  libsecauthority:
  pgdata:


networks:
  isva-network:
    name: isva-compose-net

services:

#
# Verify Access Containers
#

  isvaconfig:
    image: ${CONTAINER_BASE}:${ISVA_VERSION}
    hostname: isvaconfig
    networks:
      - isva-network
    restart: always
    environment:
#     - SNAPSHOT=${SNAPSHOT}
#     - FIXPACKS=${FIXPACKS}
      - CONTAINER_TIMEZONE=${TIMEZONE}
      - ADMIN_PWD=${ADMIN_PASSWORD}
    volumes:
      - isvaconfig:/var/shared
    ports:
      - "${LMI_IP}:9443:9443"
    depends_on:
      - openldap
      - postgresql

  isvawrprp1:
    image: ${CONTAINER_BASE}-wrp:${ISVA_VERSION}
    hostname: isvawrprp1
    networks:
      isva-network:
        aliases:
          - www.iamlab.ibm.com
    restart: always
    environment:
      - INSTANCE=rp1
#     - SNAPSHOT=${SNAPSHOT}
#     - FIXPACKS=${FIXPACKS}
      - CONTAINER_TIMEZONE=${TIMEZONE}
    volumes:
      - isvaconfig:/var/shared
    ports:
      - "${WEB1_IP}:9443:9443"
    depends_on:
      - openldap

  isvaruntime:
    image: ${CONTAINER_BASE}-runtime:${ISVA_VERSION}
    hostname: isvaruntime
    networks:
      - isva-network
    restart: always
    environment:
#     - SNAPSHOT=${SNAPSHOT}
#     - FIXPACKS=${FIXPACKS}
      - CONTAINER_TIMEZONE=${TIMEZONE}
    volumes:
      - isvaconfig:/var/shared
    depends_on:
      - openldap
      - postgresql

  isvadsc:
    image: ${CONTAINER_BASE}-dsc:${ISVA_VERSION}
    hostname: isvadsc
    networks:
      - isva-network
    restart: always
    environment:
      - INSTANCE=1
#     - SNAPSHOT=${SNAPSHOT}
#     - FIXPACKS=${FIXPACKS}
      - CONTAINER_TIMEZONE=${TIMEZONE}
    volumes:
      - isvaconfig:/var/shared

#
# Service Containers
#

  openldap:
    image: ${CONTAINER_BASE}-openldap:${LDAP_VERSION}
    hostname: openldap
    networks:
      - isva-network
    restart: always
    command: --copy-service
    environment:
      - LDAP_ADMIN_PASSWORD=Passw0rd
      - LDAP_CONFIG_PASSWORD=Passw0rd
      - LDAP_DOMAIN=ibm.com
#     - LDAP_BASE_DN=${LDAP_BASE_DN}
#     - LDAP_TLS_VERIFY_CLIENT=${LDAP_TLS_VERIFY_CLIENT}
#     - LDAP_ORGANISATION=${LDAP_ORGANISATION}
#     - LDAP_ENABLE_PORT_389=${LDAP_SSL_DISABLED}
    volumes:
      - libldap:/var/lib/ldap
      - ldapslapd:/etc/ldap/slapd.d
      - libsecauthority:/var/lib/ldap.secAuthority
      - ${HOME}/dockershare/composekeys/openldap:/container/service/slapd/assets/certs
    ports:
#      - ${LDAP_PORT}:389
      - ${LMI_IP}:1636:636

  postgresql:
    image: ${CONTAINER_BASE}-postgresql:${DB_VERSION}
    hostname: postgresql
    networks:
      - isva-network
    restart: always
    environment:
      - POSTGRES_DB=isva
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_SSL_KEYDB=/var/local/server.pem
#     - POSTGRES_UNSECURE=${DB_SSL_DISABLED}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${HOME}/dockershare/composekeys/postgresql:/var/local

  isvaop:
    image: ${CONTAINER_BASE}-oidc-provider:${ISVAOP_VERSION}
    networks:
      - isva-network
    hostname: isvaop
    restart: always
    environment:
      - CONTAINER_TIMEZONE=${TIMEZONE}
    volumes:
      - ${HOME}/dockershare/isvaop-config:/var/isvaop/config
    depends_on:
      - postgresql
